project:
  type: website
  output-dir: docs

website:
  title: "Sam Minard's ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: part_1.qmd
        text: "Project Part 1: Development and Planning"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

